use_mysql: false #Tienes que reiniciar al cambiar esta opción

mysql:
  host: "127.0.0.1"
  port: "3306"
  database: "skin_manager"
  username: "root"
  password: ""
  useSSL: false

npc_to_dissapear: #Npcs that will not be shown to player if mission has ended
  - "test"

default:
  filler_item:
    material: GRAY_STAINED_GLASS_PANE
    name: " "
  back_item:
    material: ARROW
    slot: 50
    name: "<green>Página Anterior"
  next_item:
    material: ARROW
    slot: 52
    name: "<green>Página Siguiente"
  close_item:
    material: BARRIER
    slot: 51
    name: "<red>Cerrar"
mission:
  title: "Menú de Misiones"
  slots: 54
  not_able: "<red>No puedes hacer esta misión"